pluginManagement {
	repositories {
		gradlePluginPortal()
	}
}

plugins {
	id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
	id 'dev.kikugie.stonecutter' version '0.8'
}

stonecutter {
	create(rootProject) {
		versions([
			'v1_21_4' : '1.21.4',
			'v1_21_1' : '1.21.1',
			'v1_21_6' : '1.21.6',
			'v1_21_8' : '1.21.8',
			'v1_21_9' : '1.21.9',
			'v1_21_10': '1.21.10',
			'v1_21_11': '1.21.11',
		])
	}
}
