# Better Minecraft parameter names (Parchment)
# See: https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.4
parchment_mappings_version=2025.03.23

# Environment Properties
minecraft_version=1.21.4
minecraft_version_range=[1.21.4]
neo_version=21.4.156

# Dev runtime mods (Modrinth Maven version IDs)
luckperms_modrinth_version=dKAPoPGd
bedsheet_modrinth_version=k3mznuZw

